version: '2'
volumes:
    database_data:
        driver: local
services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    php:
        build: ./docker/php/
        links:
            - mysql
        expose:
            - 9000
        volumes:
            - .:/var/www/html
    mysql:
        build: ./docker/mysql/
        expose:
            - 3306
        ports:
            - "3306:3306"
        volumes:
            - database_data:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: cart
            MYSQL_USER: cart
            MYSQL_PASSWORD: letmein
